### ISSUE TITLE
Inaccurate documentation

### ISSUE THREAD

**Issue by niftylettuce** [edj-boston/void#2]
You mention it "relies" upon `process.env` variables, however these can be overridden through `options`.  Can you please document this?  e.g. the ability to pass a configuration object and not rely on environment vars?

**Comment by edj-boston** [comment]
I added an option table in this feature branch:

* https://github.com/edj-boston/void/tree/feature/option-docs#options

Is that more clear? Let me know and I'll merge.

BTW - The code is [here](https://github.com/edj-boston/void/blob/feature/option-docs/lib/Void.js#L12), if that helps clarify

**Comment by niftylettuce** [comment]
perfect

**Comment by edj-boston** [comment]
Merged to master and published to NPM.
